### PR TITLE
Fix management SSL issues (needs separate "verify" and "fail_if_no_peer_cert" defaults)

### LINKED ISSUE #96: Management portal regression
I just upgraded to the current :management image and now the management portal no longer works,
```
curl https://127.0.0.1:15671
curl: (56) Recv failure: Connection reset by peer
```

Looking at the docker logs, I see 
```
=INFO REPORT==== 7-Jul-2016::21:31:51 ===
started SSL Listener on [::]:5671

=INFO REPORT==== 7-Jul-2016::21:31:51 ===
Management plugin started. Port: 15672
```

Seems in the recent configuration refactor the management plugin configuration got broken from running on the SSL port, 15671 to match the ssl rabbitmq port of 5671

### PR DESCRIPTION
**Pull request by tianon**
Fixes #96

### CODE REVIEW

File: docker-entrypoint.sh [hunk 1]
```diff
@@ -83,12 +113,24 @@ if [ "${#missingFiles[@]}" -gt 0 ]; then
 	exit 1
 fi
 
+# set defaults for missing values (but only after we're done with all our checking so we don't throw any of that off)
+for conf in "${allConfigKeys[@]}"; do
```
Comment (tianon) [inline docker-entrypoint.sh]: I guess this should really just loop over `${!configDefaults[@]}"`

Comment (tianon) [inline docker-entrypoint.sh]: (and thus skip the next two lines entirely)

**Comment by yosifkit** [comment]
LGTM
